# https://docs.docker.com/compose/rails/

services:
  web:
    build:
      context: .
      target: dev

    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:setup &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
      "

    environment:
      - RAILS_ENV=development

    ports:
      - '3000:3000'

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.2

    hostname: localhost

    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password

    ports:
      - '5432:5432'

    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1

volumes:
  db-data: {}
